### ISSUE TITLE
FIX 4.4

### ISSUE THREAD

**Issue by jheusser** [jvirtanen/philadelphia#2]
Do you already have plans supporting different FIX versions (FIX 4.4)? I ran a brief test connecting to a FIX 4.4 endpoint. Constructing messages is easy for it (just using different enumerations, msgtypes, and tags) however it would require some session layer configuration changes, such as logon authentication. I am not entirely familiar with all changes between the versions but it would be nice if it could be kept to purely message field differences.

Perhaps to tie this in with #1, QuickfixJ handles authentication by providing a callback on outgoing admin messages, to add further fields to the message. Perhaps something a long the lines of adding a `onLogon` method to `FIXMessageListener` which is called via `sendLogon` or similar.

**Comment by jvirtanen** [comment]
Great to hear that you are running tests. All feedback is very welcome. I personally have so far run tests against [Libtrading](https://github.com/libtrading/libtrading), [Stirling](https://github.com/penberg/stirling), and [Falcon](https://github.com/penberg/falcon).

Yes, FIX versions from FIX 4.3 onwards are on the backlog.

Regarding Logon(D), note that you can construct the message yourself and send it using `send()`instead of `sendLogon()`. However, there are header fields, such as SenderSubID(50), which are not at the moment supported on administrative messages generated by `FIXSession`. Furthermore, adding more header fields in a callback unfortunately does not work at the moment, as `FIXMessage` does not distinguish between header and body fields. This is something I have to look into a bit more.

**Comment by jheusser** [comment]
Thanks for the quick reply. Great to hear later FIX versions are in the backlog. 

Btw, the FIX 4.4 authentication fields (tags 553 / 554) are normal body fields, so I think this could work in a callback (I just added it manually to `sendLogon` test wise). But for now I'll stick to constructing a custom Logon message as you suggested, that should work as well.
