### ISSUE TITLE
Make rxBuffer capacity configurable in FIXSession

### ISSUE THREAD

**Issue by jheusser** [jvirtanen/philadelphia#5]
I believe if the SocketChannel has more bytes available than the capacity of the `rxBuffer` then this will lead to garbled FIX message parsing on the next receive call. Do you think that's correct/possible? 

Would be important to be able to adjust the capacity per session in this case.

**Comment by jvirtanen** [comment]
Good point, they should definitely be part of [`FIXConfig`](https://github.com/jvirtanen/philadelphia/blob/master/philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXConfig.java). For example:
- `FIXConfig#getRxBufferCapacity`
- `FIXConfig#getTxBufferCapacity`

Would you be interested in sending a patch? Otherwise I can fix this over the weekend.

**Comment by jheusser** [comment]
Sounds good, I'll submit a PR.

**Comment by jvirtanen** [comment]
Fixed by #6.
